name: ticky_todo
description: A colorful and stylish to-do list app built with Flutter UI/UX.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  share_plus: ^10.0.2
  image_picker: ^1.1.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  cloud_functions: ^5.1.2
  pdf: ^3.11.1 # Untuk menghasilkan PDF (fitur ekspor PDF)
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Ditambahkan untuk analisis kode
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/logo.png
    - assets/icons/work.png
    - assets/icons/personal.png
    - assets/icons/study.png

