// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Olq-Ste_vIFQSv8c8dRoRFlqie-CpiU',
    appId: '1:628738659262:web:3cb5649a42e8abede5dfef',
    messagingSenderId: '628738659262',
    projectId: 'to-do-list-36f38',
    authDomain: 'to-do-list-36f38.firebaseapp.com',
    databaseURL: 'https://to-do-list-36f38-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-36f38.firebasestorage.app',
    measurementId: 'G-PH4TPZK26N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvLyz6MaDiILSo7pXljdn8kcw2J7sG6OE',
    appId: '1:628738659262:android:0ba42e3dd132ba6ae5dfef',
    messagingSenderId: '628738659262',
    projectId: 'to-do-list-36f38',
    databaseURL: 'https://to-do-list-36f38-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-36f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvKWNU01xD-XMDTsNleoN-BC47fABl67M',
    appId: '1:628738659262:ios:fddf18c4d519780ee5dfef',
    messagingSenderId: '628738659262',
    projectId: 'to-do-list-36f38',
    databaseURL: 'https://to-do-list-36f38-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-36f38.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvKWNU01xD-XMDTsNleoN-BC47fABl67M',
    appId: '1:628738659262:ios:fddf18c4d519780ee5dfef',
    messagingSenderId: '628738659262',
    projectId: 'to-do-list-36f38',
    databaseURL: 'https://to-do-list-36f38-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-36f38.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Olq-Ste_vIFQSv8c8dRoRFlqie-CpiU',
    appId: '1:628738659262:web:6c91aed43334ee33e5dfef',
    messagingSenderId: '628738659262',
    projectId: 'to-do-list-36f38',
    authDomain: 'to-do-list-36f38.firebaseapp.com',
    databaseURL: 'https://to-do-list-36f38-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-36f38.firebasestorage.app',
    measurementId: 'G-1VBRP86MME',
  );
}
